'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { AdButton as AdButtonElement, defineCustomElement as defineAdButton } from "@agado/components/dist/components/ad-button.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type AdButtonEvents = { onPressAndHold: EventName<CustomEvent<void>> };

const AdButton: StencilReactComponent<AdButtonElement, AdButtonEvents> = /*@__PURE__*/ createComponent<AdButtonElement, AdButtonEvents>({
    tagName: 'ad-button',
    elementClass: AdButtonElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onPressAndHold: 'pressAndHold' } as AdButtonEvents,
    defineCustomElement: defineAdButton
});

export default AdButton;
